core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('payment/<ref>/', views.payment, name='payment'),
    path('checkout/flutterwave/verification/', views.FlutterWaveVerification.as_view(), name="flutterwave-verification"),
    path('export/', views.export_page, name="export")
]

school2hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.utils import timezone
import string, random

class Student(models.Model):

    LEVEL = (
        ('100', '100 L'),
        ('200', '200 L'),
        ('300', '300 L'),
        ('400', '400 L'),
        ('500', '500 L'),
        ('600', '600 L'),
    )
    matric = models.CharField(max_length=10)
    email = models.EmailField()
    name = models.CharField(max_length=255)
    level = models.CharField(max_length=3, choices=LEVEL)
    phone = models.CharField(max_length=11)
    total_gb = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    amount = models.IntegerField(default=0)
    ref = models.CharField(max_length=300, )
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.matric

    def save(self, *args, **kwargs):
        def rand():
            rand = "".join(random.choices(string.ascii_lowercase, k=20))
            return rand
        
        if self.total_gb < 11 :
            amount = self.total_gb * 264
            self.amount = amount
        elif self.total_gb > 10 and self.total_gb < 21 :
            amount = self.total_gb * 250
            self.amount = amount
        elif self.total_gb > 20 and self.total_gb < 31 :
            amount = self.total_gb * 230
            self.amount = amount
        else:
            amount = self.total_gb * 200
            self.amount = amount
        if self.ref == '':
            self.ref = f'{self.phone}{self.total_gb}{rand()}'
        self.created = timezone.now()
        super().save(*args, **kwargs)

class Export(models.Model):
    # MONTH = (
    #     (1, 'JAN'),
    #     (2, 'FEB'),
    #     (3, 'MAR'),
    #     (4, 'APR'),
    #     (5, 'MAY'),
    #     (6, 'JUN'),
    #     (7, 'JUL'),
    #     (8, 'AUG'),
    #     (9, 'SEP'),
    #     (10, 'OCT'),
    #     (11, 'NOV'),
    #     (12, 'DEC'),

    # )
    

    month = models.IntegerField()
    day = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

core/forms.py
from django.forms import ModelForm
from .models import *
from django import forms

class DataForm(ModelForm):
    class Meta:
        model = Student
        exclude = ['created', 'amount', 'ref', 'status']

class ExportForm(ModelForm):
    class Meta:
        model = Export
        exclude = ['date',]

core/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .forms import DataForm, ExportForm
from django.contrib import messages
from .models import Student
from django.views import View
import requests, json
from django.conf import settings
from datetime import datetime
from django.utils import timezone
import csv

def Home(request):
    form = DataForm()

    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            number = form.cleaned_data.get('phone') 
            matric = form.cleaned_data.get('matric') 
            student = Student.objects.filter(phone=number, matric=matric, status=False)[0]
            ref = student.ref
            msg = 'You order is being processed'
            messages.info(request, msg)
            return redirect('payment', ref=ref)

    context = {
        'form' : form
    }
    return render(request, 'homee.html', context)

def payment(request, ref):
    student = Student.objects.get(ref=ref)
    context = {
        'student' : student,
    }
    return render(request, 'payment.html', context)

class FlutterWaveVerification(View):
    def get(self, *args, **kwargs):
        tx_ref = self.request.GET.get('tx_ref', '')
        transaction_id = self.request.GET.get('transaction_id', '')
        status = self.request.GET.get('status', '')
        student = Student.objects.get(ref=tx_ref)

        if status == 'successful':
            url = f'https://api.flutterwave.com/v3/transactions/{transaction_id}/verify'
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {settings.FLUTTER_SECRET_KEY}',
            }
            res = requests.get(url, headers=headers)
            print(res)
            
            response = res.json()
            if response['status'] == 'success' and response['data']['tx_ref'] == student.ref:
                student.status = True
                student.save()
                msg = f"Dear {student.name}, You payment has been verified and the data will be credited to your sim soon. Thank you!"
                messages.info(self.request, msg)
                return redirect('home')
            else:
                student = Student.objects.get(ref=tx_ref)
                ref = student.ref
                msg = f"Dear {student.name}, Your order with reference: {tx_ref} is not yet verified. Try making the payment again. Please save this Transaction id: {transaction_id} for record process."
                messages.info(self.request, msg)
                return redirect('payment', ref =ref)
        else:
            student = Student.objects.get(ref=tx_ref)
            ref = student.ref
            msg = f"Dear {student.name}, Your payment with reference: {tx_ref} is was not successful.. Try making the payment again. Please save this Transaction id: {transaction_id} for record process."
            messages.info(self.request, msg)
            return redirect('payment', ref=ref)

def export_page (request):
    form = ExportForm()

    if request.method == 'POST':
        form = ExportForm(request.POST)
        print("form entry point")
        if form.is_valid():
            month = form.cleaned_data.get('month')
            day = form.cleaned_data.get('day')
            if month != '' and day != '':
                start_date_naive=datetime(month=month, day=day, year=2021)
                print(f'{start_date_naive} entry')
                current_tz = timezone.get_current_timezone()
                start_date = current_tz.localize(start_date_naive)
                end_date=timezone.now()
                response = HttpResponse(content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename="completed_reg_exports.csv"'
                writer = csv.writer(response)
                writer.writerow(['id', 'matric', 'email', 'name', 'phone', 'total_gb', 'created', 'amount'])
                data = Student.objects.filter(created__range=[start_date,end_date], status=True).values_list('id', 'matric', 'email', 'name', 'phone', 'total_gb', 'created', 'amount')
                print('database connection stage')
                for entry in data:
                    writer.writerow(entry)
                    print('data entry stage')
                return response
            else :
                msg = f"Error Exporting, please select date and try again"
                print('error with month and date.')
                messages.info(request, msg)
                return redirect('export')
        else :
                msg = f"Form is not valid"
                print('Error with form validity')
                messages.info(request, msg)
                return redirect('export')

    context = {
        'form':form
    }
    return render (request, 'export.html', context)

core/templates/export.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from portotheme.com/html/porto_ecommerce/demo_22/checkout-shipping.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Dec 2020 11:27:54 GMT -->

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Export Page</title>


    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icons/favicon.ico' %}">


    <script type="text/javascript">
        WebFontConfig = {
            google: { families: ['Open+Sans:300,400,600,700,800', 'Poppins:300,400,500,600,700'] }
        };
        (function (d) {
            var wf = d.createElement('script'), s = d.scripts[0];
            wf.src = '{% static "assets/js/webfont.js" %}';
            wf.async = true;
            s.parentNode.insertBefore(wf, s);
        })(document);
    </script>

    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}">
</head>

<body>
    <div class="page-wrapper">
        <header class="header">

            <div class="header-middle">
                <div class="container">
                    <div class="header-left">
                        <button class="mobile-menu-toggler" type="button">
                            <i class="icon-menu"></i>
                        </button>
                        <a href="" class="logo">
                            <img src="{% static 'assets/images/logo1.jpg' %}" height="60" width="60" alt="Porto Logo">
                        </a>
                    </div>
                </div><!-- End .container -->
            </div><!-- End .header-middle -->


        </header><!-- End .header -->

        <main class="main">

            <div class="container">
                <ul class="checkout-progress-bar">

                </ul>
                <div class="row">
                    <div class="col-lg-8">
                        <ul class="checkout-steps">
                            <li>
                                <h2 class="step-title">Export Page</h2>

                                {%if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
          
          {{message}}
          <button
            type="button"
            {%
            if
            message.tags
            %}
            class="{{message.tags}}"
            {%
            endif
            %}
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
          
        </div>
        {% endfor %}
        {% endif %}
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    
                                    <div class="form-group required-field">
                                        <label>Month (Between 1 - 12) </label>
                                        <input type="number" class="form-control" max="12" name="month" max="2" id="id_month" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group required-field">
                                        <label>Day (Between 1 - 31).  </label>
                                        <input type="number" class="form-control" max="31" maxlength="2" name="day" id="id_day" required>
                                    </div><!-- End .form-group -->
                                    
                                    <div class="form-footer">
                                        <button type="submit" class="btn btn-primary">Export</button>
                                        
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div><!-- End .col-lg-8 -->


                </div><!-- End .container -->

                <div class="mb-6"></div><!-- margin -->
        </main><!-- End .main -->

        <footer class="footer">
            <div class="footer-top">
                <div class="container">

                </div>
            </div>

            <div class="container">
                <div class="footer-middle   ">
                    <div class="row">

                        <div class="footer-bottom">
                            <p class="footer-copyright">Built by School2 Hub &copy; 2020. All Rights Reserved</p>
                            
                        </div><!-- End .footer-bottom -->
                    </div>
        </footer><!-- End .footer -->
    </div><!-- End .page-wrapper -->

    <a id="scroll-top" href="#top" title="Top" role="button"><i class="icon-angle-up"></i></a>

    <!-- Plugins JS File -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins.min.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.min.js' %}"></script>
</body>

<!-- Mirrored from portotheme.com/html/porto_ecommerce/demo_22/checkout-shipping.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Dec 2020 11:27:54 GMT -->

</html>

core/templates/homee.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from portotheme.com/html/porto_ecommerce/demo_22/checkout-shipping.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Dec 2020 11:27:54 GMT -->

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Glo Custom Data Plan for Unilorin Students</title>


    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icons/favicon.ico' %}">


    <script type="text/javascript">
        WebFontConfig = {
            google: { families: ['Open+Sans:300,400,600,700,800', 'Poppins:300,400,500,600,700'] }
        };
        (function (d) {
            var wf = d.createElement('script'), s = d.scripts[0];
            wf.src = '{% static "assets/js/webfont.js" %}';
            wf.async = true;
            s.parentNode.insertBefore(wf, s);
        })(document);
    </script>

    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}">
</head>

<body>
    <div class="page-wrapper">
        <header class="header">

            <div class="header-middle">
                <div class="container">
                    <div class="header-left">
                        <button class="mobile-menu-toggler" type="button">
                            <i class="icon-menu"></i>
                        </button>
                        <a href="" class="logo">
                            <img src="{% static 'assets/images/logo1.jpg' %}" height="60" width="60" alt="Porto Logo">
                        </a>
                    </div>
                </div><!-- End .container -->
            </div><!-- End .header-middle -->


        </header><!-- End .header -->

        <main class="main">

            <div class="container">
                <ul class="checkout-progress-bar">

                </ul>
                <div class="row">
                    <div class="col-lg-8">
                        <ul class="checkout-steps">
                            <li>
                                <h2 class="step-title">GLO Custom Data Plan Registration Page</h2>

                                {%if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
          
          {{message}}
          <button
            type="button"
            {%
            if
            message.tags
            %}
            class="{{message.tags}}"
            {%
            endif
            %}
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
          
        </div>
        {% endfor %}
        {% endif %}
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group required-field">
                                        <label>Full Name </label>
                                        <input type="text" class="form-control" name="name" maxlength="255" id="id_name" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group required-field">
                                        <label>Matric No (Format: 17/20GB973)</label>
                                        <input type="text" class="form-control" name="matric" maxlength="10" id="id_matric" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label>Email </label>
                                        <input type="email" name="email" maxlength="255" id="id_email" required class="form-control">
                                    </div><!-- End .form-group -->

                                    <div class="form-group required-field">
                                        <label>Phone number (Glo number only. Format: 080********) </label>
                                        <input type="text" class="form-control" name="phone" maxlength="11" id="id_phone" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group required-field">
                                        <label>How many GB? </label>
                                        <input type="number" class="form-control" name="total_gb" id="id_total_gb" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label>Level</label>
                                        <div class="select-custom">
                                            <select class="form-control" name="level" id="id_level" required>
                                                <option value="USA" selected>Select level</option>
                                                <option value="100">100 L</option>
                                                <option value="200">200 L</option>
                                                <option value="300">300 L</option>
                                                <option value="400">400 L</option>
                                                <option value="500">500 L</option>
                                                <option value="600">600 L</option>
                                            </select>
                                        </div><!-- End .select-custom -->
                                    </div><!-- End .form-group -->

                                    <div class="form-footer">
                                        <button type="submit" class="btn btn-primary">PROCEED</button>
                                        
                                    </div>
                                </form>
                            </li>


                        </ul>
                    </div><!-- End .col-lg-8 -->




                </div><!-- End .container -->

                <div class="mb-6"></div><!-- margin -->
        </main><!-- End .main -->

        <footer class="footer">
            <div class="footer-top">
                <div class="container">

                </div>
            </div>

            <div class="container">
                <div class="footer-middle   ">
                    <div class="row">

                        <div class="footer-bottom">
                            <p class="footer-copyright">Built by School2 Hub &copy; 2020. All Rights Reserved</p>
                            
                        </div><!-- End .footer-bottom -->
                    </div>
        </footer><!-- End .footer -->
    </div><!-- End .page-wrapper -->

    <a id="scroll-top" href="#top" title="Top" role="button"><i class="icon-angle-up"></i></a>

    <!-- Plugins JS File -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins.min.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.min.js' %}"></script>
</body>

<!-- Mirrored from portotheme.com/html/porto_ecommerce/demo_22/checkout-shipping.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Dec 2020 11:27:54 GMT -->

</html>

core/templates/payment.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from portotheme.com/html/porto_ecommerce/demo_22/checkout-shipping.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Dec 2020 11:27:54 GMT -->

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Glo Custom Data Plan for Unilorin Students</title>


    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/icons/favicon.ico' %}">


    <script type="text/javascript">
        WebFontConfig = {
            google: { families: ['Open+Sans:300,400,600,700,800', 'Poppins:300,400,500,600,700'] }
        };
        (function (d) {
            var wf = d.createElement('script'), s = d.scripts[0];
            wf.src = '{% static "assets/js/webfont.js" %}';
            wf.async = true;
            s.parentNode.insertBefore(wf, s);
        })(document);
    </script>

    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}">
</head>

<body>
    <div class="page-wrapper">
        <header class="header">

            <div class="header-middle">
                <div class="container">
                    <div class="header-left">
                        <button class="mobile-menu-toggler" type="button">
                            <i class="icon-menu"></i>
                        </button>
                        <a href="" class="logo">
                            <img src="{% static 'assets/images/logo1.jpg' %}" height="60" width="60" alt="Porto Logo">
                        </a>
                    </div>
                </div><!-- End .container -->
            </div><!-- End .header-middle -->


        </header><!-- End .header -->

        <main class="main">

            <div class="container">
                <ul class="checkout-progress-bar">

                </ul>
                <div class="row">
                    <div class="col-lg-8">
                        <ul class="checkout-steps">
                            <li>
                                <h2 class="step-title">Confirm your order and Make Payment</h2>
                                <br>
                                <br>
                                <h3>Verify Information</h3>                                
                                {%if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
          
          {{message}}
          <button
            type="button"
            {%
            if
            message.tags
            %}
            class="{{message.tags}}"
            {%
            endif
            %}
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
          
        </div>
        {% endfor %}
        {% endif %}
                                <div class="alert alert-success" role="alert">
                                    Hello, <strong>{{student.name}}!</strong>  Please check the details to check for errors. The Price of {{student.total_gb}}GB is #{{student.amount}}. Do note that you'll be charged a token for processing.
                                </div><!-- End .alert -->
                                
                                <div class="card">
                                    <div class="card-header">
                                        Details
                                        
                                    </div><!-- End .card-header -->
        
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <h4 class="">Personal Details</h4>
                                                <br>
                                                <address>
                                                    <p> <strong> Matric No.:</strong>    {{student.matric}}</p><br>
                                                    <p><strong> Name: </strong>   {{student.name}}</p> <br>
                                                    <p> <strong> Email: </strong>   {{student.email}}</p> <br>
                                                </address>
                                            </div>
                                            <div class="col-md-6">
                                                <h4 class="">Data Details</h4>
                                                <address>
                                                    <p> <strong> Total GB requested:</strong>    {{student.total_gb}}</p><br>
                                                    <p><strong> Price: </strong>   #{{student.amount}}</p> <br>
                                                    <p> <strong> Transaction ref: </strong>   {{student.ref}}</p> <br>
                                                </address>
                                            </div>
                                        </div>
                                        <form>
                                            <script src="https://checkout.flutterwave.com/v3.js"></script>
                                            <div class="form-footer">
                                                <button type="button" onClick="makePayment()" class="btn btn-primary">Click here to make payment online</button>
        
                                            </div>
                                        </form>
                                        
                                    </div><!-- End .card-body -->
                                </div><!-- End
                                
                                
                            </li>


                        </ul>
                    </div><!-- End .col-lg-8 -->




                </div><!-- End .container -->

                <div class="mb-6"></div><!-- margin -->
        </main><!-- End .main -->

        <footer class="footer">
            <div class="footer-top">
                <div class="container">

                </div>
            </div>

            <div class="container">
                <div class="footer-middle   ">
                    <div class="row">

                        <div class="footer-bottom">
                            <p class="footer-copyright">Built by School2 Hub &copy; 2020. All Rights Reserved</p>
                            
                        </div><!-- End .footer-bottom -->
                    </div>
        </footer><!-- End .footer -->
    </div><!-- End .page-wrapper -->

    <a id="scroll-top" href="#top" title="Top" role="button"><i class="icon-angle-up"></i></a>

    <!-- Plugins JS File -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins.min.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.min.js' %}"></script>

    
      
      <script>
          price = {{student.amount}}
            price += price * 0.02
        function makePayment() {
          FlutterwaveCheckout({
            public_key: "FLWPUBK_TEST-88d541ad7d3c9776a006f3d0611d5d98-X",
            tx_ref: "{{student.ref}}",
            amount: price,
            currency: "NGN",
            country: "NG",
            payment_options: "card, ussd, banktransfer",
            redirect_url: // specified redirect URL
            "https://unilorin-glo.herokuapp.com/checkout/flutterwave/verification/",
            customer: {
              email: "{{student.email}}",
              phone_number: "{{student.phone}}",
              name: "{{student.name}}",
              matric: "{{student.matric}}",
              data: "{{student.total_gb}}",
            },
            callback: function (data) {
              console.log(data);
            },
            onclose: function() {
              // close modal
            },
            customizations: {
              title: "Glo Data Payment",
              description: "Please complete payment to activate your glo payment",
              logo: "{% static 'assets/images/logo1.jpg'%}",
            },
          });
        }
      </script>
</body>

<!-- Mirrored from portotheme.com/html/porto_ecommerce/demo_22/checkout-shipping.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Dec 2020 11:27:54 GMT -->

</html>